name: MinecraftHeads
main: com.edawg878.minecraftheads.MinecraftHeads
version: 1.06
author: EDawg878
website: http://EDawg878.com/
commands:
    mcheads:
        default: true
        description: Base command of MinecraftHeads
        aliases: [mch, head]