name: MinecraftHeads
main: com.edawg878.minecraftheads.MinecraftHeads
version: 1
author: EDawg878
website: EDawg878.com
commands:
    mcheads:
        default: true
        description: Base command of Minecraft Heads
        usage: /<command> help